package ca.six.router2.plugin;

import com.android.utils.FileUtils
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction;

public class CreateFileTask extends DefaultTask {
    @Input public File baseFile;
    @Input public String content;

    public CreateFileTask() {
        group = 'router2'
    }

    @TaskAction
    public void run() {
        // 1. create the path and file
        if (!baseFile.exists()) {
            baseFile.mkdirs()
        }
        File tmp = FileUtils.join(baseFile, "ca", "six", "router2")
        if (!tmp.exists()) {
            tmp.mkdirs()  //▼ 注意不能是mkdir()，这里有多个目录要生成的
        }

        File target = new File(tmp, "ModuleInfo.java")
        if (!target.exists()) {
            target.createNewFile()
        }

        // 2. generate file content
        def sb = new StringBuilder()
        sb.append("package ca.six.router2;\n")
        sb.append("\n")
        sb.append("// Generated by Router2. Do not edit it.\n")
        sb.append("public class ModuleInfo {\n")
        sb.append("\tpublic static final String MODULES = \"%inserted%\";\n")
        sb.append("}\n")
        String result = sb.toString().replace("%inserted%", content)

        // 3. write file
        def pw = new PrintWriter(target)
        pw.print(result)
        pw.flush()
        pw.close()

    }
}
